 {
    "ip": "ip.aternos.me",
    "port": "30664",
    "name": "PappuBhai",
    "auto-reconnect": "true",
    "comment": "If True Then Bot Will Skip Night",
    "login-enabled": "true",
    "comment": "If True Then Bot Will Login/Register",
    "register-cmd": "/register {password} {password}",
    "login-cmd": "/login {password}"
   }
